apiVersion: v2
name: magda-auth-internal
description: A MAGDA authentication plugin supports local password authentication.
version: "3.0.0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda-auth-internal"
sources: [ "https://github.com/magda-io/magda-auth-internal" ]
dependencies:
  - name: magda-common
    version: "2.1.1"
    repository: "oci://ghcr.io/magda-io/charts"
