apiVersion: v2
name: magda-auth-internal
description: A MAGDA authentication plugin supports local password authentication.
version: "1.0.1"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda-auth-internal"
sources: ["https://github.com/magda-io/magda-auth-internal"]

